import { TeachingMode, LeadStatus, Role } from "@/types";

// ─── Subjects ────────────────────────────────────────────────────────────────

export const SUBJECTS = [
  { id: "sub_01", name: "10th CBSE Mathematics" },
  { id: "sub_02", name: "10th CBSE Science" },
  { id: "sub_03", name: "10th CBSE English" },
  { id: "sub_04", name: "10th State Mathematics" },
  { id: "sub_05", name: "10th State Science" },
  { id: "sub_06", name: "12th CBSE Physics" },
  { id: "sub_07", name: "12th CBSE Chemistry" },
  { id: "sub_08", name: "12th CBSE Mathematics" },
  { id: "sub_09", name: "12th State Physics" },
  { id: "sub_10", name: "12th State Chemistry" },
  { id: "sub_11", name: "12th State Mathematics" },
  { id: "sub_12", name: "8th CBSE Mathematics" },
  { id: "sub_13", name: "8th CBSE Science" },
  { id: "sub_14", name: "8th CBSE English" },
  { id: "sub_15", name: "JEE Mains Mathematics" },
  { id: "sub_16", name: "JEE Mains Physics" },
  { id: "sub_17", name: "NEET Biology" },
  { id: "sub_18", name: "NEET Chemistry" },
  { id: "sub_19", name: "Computer Science (Python)" },
  { id: "sub_20", name: "Computer Science (C++)" },
] as const;

// ─── Mock Tutor Profiles ─────────────────────────────────────────────────────

export const MOCK_TUTORS = [
  {
    id: "tutor_01",
    userId: "user_01",
    phone: "9847123456",
    collegeName: "CUSAT - Cochin University of Science and Technology",
    degree: "B.Tech Information Technology",
    yearOfStudy: 3,
    bio: "Passionate about making Math simple and fun! I've been tutoring students in my neighborhood in Kalamassery for the past 2 years. My approach focuses on building strong fundamentals through real-world problem solving. I scored 98% in my 12th CBSE board exams and have helped over 15 students improve their grades significantly.",
    teachingMode: TeachingMode.BOTH,
    idCardUrl: null,
    profilePictureUrl: null,
    isVerified: true,
    subjects: [
      { id: "sub_01", name: "10th CBSE Mathematics" },
      { id: "sub_08", name: "12th CBSE Mathematics" },
      { id: "sub_15", name: "JEE Mains Mathematics" },
    ],
    user: {
      id: "user_01",
      name: "Arjun Menon",
      email: "arjun.menon@cusat.ac.in",
      image: null,
      role: Role.TUTOR,
      createdAt: new Date("2025-01-15"),
      updatedAt: new Date("2025-03-20"),
    },
    createdAt: new Date("2025-01-15"),
    updatedAt: new Date("2025-03-20"),
  },
  {
    id: "tutor_02",
    userId: "user_02",
    phone: "9562234567",
    collegeName: "CUSAT - Cochin University of Science and Technology",
    degree: "B.Tech Information Technology",
    yearOfStudy: 4,
    bio: "Final year B.Tech IT student with a strong grasp on Physics and Mathematics. I teach at homes around Edappally and Kakkanad. My students consistently score above 90% in their board exams. I use visual aids and interactive experiments to make Physics concepts come alive. Available on weekends and evenings.",
    teachingMode: TeachingMode.OFFLINE,
    idCardUrl: null,
    profilePictureUrl: null,
    isVerified: true,
    subjects: [
      { id: "sub_06", name: "12th CBSE Physics" },
      { id: "sub_09", name: "12th State Physics" },
      { id: "sub_16", name: "JEE Mains Physics" },
    ],
    user: {
      id: "user_02",
      name: "Sneha Krishnan",
      email: "sneha.k@cusat.ac.in",
      image: null,
      role: Role.TUTOR,
      createdAt: new Date("2024-11-05"),
      updatedAt: new Date("2025-02-14"),
    },
    createdAt: new Date("2024-11-05"),
    updatedAt: new Date("2025-02-14"),
  },
  {
    id: "tutor_03",
    userId: "user_03",
    phone: "8907345678",
    collegeName: "CUSAT - Cochin University of Science and Technology",
    degree: "B.Tech Information Technology",
    yearOfStudy: 2,
    bio: "Second year IT student who loves teaching younger students! I focus on 8th and 10th standard CBSE Science and Math. Being a recent school graduate myself, I understand exactly what challenges students face with the current syllabus. I'm available for online sessions via Google Meet and can come to homes near Aluva and Kalamassery.",
    teachingMode: TeachingMode.BOTH,
    idCardUrl: null,
    profilePictureUrl: null,
    isVerified: false,
    subjects: [
      { id: "sub_01", name: "10th CBSE Mathematics" },
      { id: "sub_02", name: "10th CBSE Science" },
      { id: "sub_12", name: "8th CBSE Mathematics" },
      { id: "sub_13", name: "8th CBSE Science" },
    ],
    user: {
      id: "user_03",
      name: "Amal Thomas",
      email: "amal.t@cusat.ac.in",
      image: null,
      role: Role.TUTOR,
      createdAt: new Date("2025-02-20"),
      updatedAt: new Date("2025-04-10"),
    },
    createdAt: new Date("2025-02-20"),
    updatedAt: new Date("2025-04-10"),
  },
  {
    id: "tutor_04",
    userId: "user_04",
    phone: "7012456789",
    collegeName: "CUSAT - Cochin University of Science and Technology",
    degree: "M.Sc Mathematics",
    yearOfStudy: 1,
    bio: "Gold medalist in B.Sc Mathematics from MG University. Currently pursuing my Master's at CUSAT. I specialize in higher-level mathematics including JEE preparation. My method involves breaking down complex problems into simple, digestible steps. I conduct classes at my place in Thrikkakara and also offer online sessions.",
    teachingMode: TeachingMode.ONLINE,
    idCardUrl: null,
    profilePictureUrl: null,
    isVerified: true,
    subjects: [
      { id: "sub_08", name: "12th CBSE Mathematics" },
      { id: "sub_11", name: "12th State Mathematics" },
      { id: "sub_15", name: "JEE Mains Mathematics" },
    ],
    user: {
      id: "user_04",
      name: "Devika Nair",
      email: "devika.nair@cusat.ac.in",
      image: null,
      role: Role.TUTOR,
      createdAt: new Date("2025-03-01"),
      updatedAt: new Date("2025-04-15"),
    },
    createdAt: new Date("2025-03-01"),
    updatedAt: new Date("2025-04-15"),
  },
  {
    id: "tutor_05",
    userId: "user_05",
    phone: "9446567890",
    collegeName: "CUSAT - Cochin University of Science and Technology",
    degree: "B.Tech Information Technology",
    yearOfStudy: 3,
    bio: "Experienced in teaching Chemistry and Biology for NEET aspirants. I combine my IT background with science teaching to create interactive digital study materials for my students. Available for home tuitions in the Palarivattom and Vyttila areas. I've helped 5 students clear NEET in the last cycle.",
    teachingMode: TeachingMode.OFFLINE,
    idCardUrl: null,
    profilePictureUrl: null,
    isVerified: true,
    subjects: [
      { id: "sub_07", name: "12th CBSE Chemistry" },
      { id: "sub_10", name: "12th State Chemistry" },
      { id: "sub_17", name: "NEET Biology" },
      { id: "sub_18", name: "NEET Chemistry" },
    ],
    user: {
      id: "user_05",
      name: "Rahul Sharma",
      email: "rahul.s@cusat.ac.in",
      image: null,
      role: Role.TUTOR,
      createdAt: new Date("2024-09-12"),
      updatedAt: new Date("2025-01-30"),
    },
    createdAt: new Date("2024-09-12"),
    updatedAt: new Date("2025-01-30"),
  },
  {
    id: "tutor_06",
    userId: "user_06",
    phone: "8086678901",
    collegeName: "CUSAT - Cochin University of Science and Technology",
    degree: "B.Sc Physics",
    yearOfStudy: 3,
    bio: "Physics enthusiast who loves conducting experiments at home to explain concepts. I teach 10th and 12th State board Physics and Science. My students in Fort Kochi and Mattancherry areas love the hands-on approach. I also offer affordable group tuition sessions for 3-4 students at a time.",
    teachingMode: TeachingMode.BOTH,
    idCardUrl: null,
    profilePictureUrl: null,
    isVerified: false,
    subjects: [
      { id: "sub_05", name: "10th State Science" },
      { id: "sub_09", name: "12th State Physics" },
      { id: "sub_02", name: "10th CBSE Science" },
    ],
    user: {
      id: "user_06",
      name: "Fathima Zahra",
      email: "fathima.z@cusat.ac.in",
      image: null,
      role: Role.TUTOR,
      createdAt: new Date("2025-01-08"),
      updatedAt: new Date("2025-03-25"),
    },
    createdAt: new Date("2025-01-08"),
    updatedAt: new Date("2025-03-25"),
  },
  {
    id: "tutor_07",
    userId: "user_07",
    phone: "9037789012",
    collegeName: "CUSAT - Cochin University of Science and Technology",
    degree: "B.Tech Information Technology",
    yearOfStudy: 4,
    bio: "Coding and Mathematics go hand in hand! I teach Computer Science (Python & C++), along with 10th and 12th Math. My unique approach integrates coding exercises with mathematical concepts, helping students develop computational thinking. Available for online classes anytime and offline classes in Ernakulam South area.",
    teachingMode: TeachingMode.BOTH,
    idCardUrl: null,
    profilePictureUrl: null,
    isVerified: true,
    subjects: [
      { id: "sub_01", name: "10th CBSE Mathematics" },
      { id: "sub_04", name: "10th State Mathematics" },
      { id: "sub_19", name: "Computer Science (Python)" },
      { id: "sub_20", name: "Computer Science (C++)" },
    ],
    user: {
      id: "user_07",
      name: "Vishnu Prasad",
      email: "vishnu.p@cusat.ac.in",
      image: null,
      role: Role.TUTOR,
      createdAt: new Date("2024-08-20"),
      updatedAt: new Date("2025-04-01"),
    },
    createdAt: new Date("2024-08-20"),
    updatedAt: new Date("2025-04-01"),
  },
  {
    id: "tutor_08",
    userId: "user_08",
    phone: "9188890123",
    collegeName: "CUSAT - Cochin University of Science and Technology",
    degree: "B.Tech Information Technology",
    yearOfStudy: 2,
    bio: "Enthusiastic English and Science tutor for middle school students. I believe every child can excel with the right guidance and patience. I specialize in making English grammar fun through stories and games. Available for home tuitions in Tripunithura and Maradu areas. Weekend batch classes also available.",
    teachingMode: TeachingMode.OFFLINE,
    idCardUrl: null,
    profilePictureUrl: null,
    isVerified: false,
    subjects: [
      { id: "sub_03", name: "10th CBSE English" },
      { id: "sub_13", name: "8th CBSE Science" },
      { id: "sub_14", name: "8th CBSE English" },
    ],
    user: {
      id: "user_08",
      name: "Lakshmi Priya",
      email: "lakshmi.p@cusat.ac.in",
      image: null,
      role: Role.TUTOR,
      createdAt: new Date("2025-04-01"),
      updatedAt: new Date("2025-04-20"),
    },
    createdAt: new Date("2025-04-01"),
    updatedAt: new Date("2025-04-20"),
  },
];

// ─── Mock Leads ──────────────────────────────────────────────────────────────

export const MOCK_LEADS = [
  {
    id: "lead_01",
    parentId: "user_p01",
    tutorProfileId: "tutor_01",
    message:
      "Hi Arjun, my son is in 10th CBSE and needs help with Math. He's scoring around 60% currently. Can you help bring it up to 85+? We're in Kalamassery, very close to CUSAT.",
    status: LeadStatus.ACCEPTED,
    createdAt: new Date("2025-03-10"),
    updatedAt: new Date("2025-03-11"),
  },
  {
    id: "lead_02",
    parentId: "user_p02",
    tutorProfileId: "tutor_02",
    message:
      "Sneha, my daughter is preparing for her 12th board exams and needs Physics tuition. We live in Kakkanad. What's your fee structure?",
    status: LeadStatus.PENDING,
    createdAt: new Date("2025-04-05"),
    updatedAt: new Date("2025-04-05"),
  },
  {
    id: "lead_03",
    parentId: "user_p03",
    tutorProfileId: "tutor_05",
    message:
      "Looking for a NEET Chemistry tutor for my son. He's in 12th and the exam is in 6 months. Can we start immediately?",
    status: LeadStatus.ACCEPTED,
    createdAt: new Date("2025-02-20"),
    updatedAt: new Date("2025-02-21"),
  },
  {
    id: "lead_04",
    parentId: "user_p01",
    tutorProfileId: "tutor_07",
    message:
      "Vishnu, my son wants to learn Python programming alongside his 10th Math. Is that possible in the same session?",
    status: LeadStatus.DECLINED,
    createdAt: new Date("2025-03-15"),
    updatedAt: new Date("2025-03-16"),
  },
];

// ─── College Options for Kochi Area ──────────────────────────────────────────

export const COLLEGES = [
  "CUSAT - Cochin University of Science and Technology",
  "Rajagiri School of Engineering & Technology",
  "Model Engineering College, Thrikkakara",
  "Government Engineering College, Thrissur",
  "College of Engineering Munnar",
  "Mar Athanasius College of Engineering",
  "Federal Institute of Science and Technology (FISAT)",
  "Toc H Institute of Science and Technology",
  "Amal Jyothi College of Engineering",
  "St. Joseph's College of Engineering and Technology",
  "Other",
] as const;

// ─── Degree Options ──────────────────────────────────────────────────────────

export const DEGREES = [
  "B.Tech Information Technology",
  "B.Tech Computer Science",
  "B.Tech Electronics & Communication",
  "B.Tech Electrical Engineering",
  "B.Tech Mechanical Engineering",
  "B.Tech Civil Engineering",
  "B.Sc Physics",
  "B.Sc Chemistry",
  "B.Sc Mathematics",
  "B.Sc Computer Science",
  "M.Sc Physics",
  "M.Sc Chemistry",
  "M.Sc Mathematics",
  "M.Tech",
  "MCA",
  "BCA",
  "Other",
] as const;
